In [1]:
import pandas as pd
import numpy as np
import json
from pathlib import Path

In [ ]:
file_path = "/home/stanford/catkin_ws/src/Autonomous-Surgical-Robot-Data/Needle Transfer Chetan/Demo6/episode_000000.parquet"
df_reference = pd.read_parquet(file_path)
df_reference.head()

observation.state  \
0  [1.076010372088713, -0.8717434618548155, 0.207...   
1  [1.076010372088713, -0.8717434618548155, 0.207...   
2  [1.076010372088713, -0.8717434618548155, 0.207...   
3  [1.076010372088713, -0.8717434618548155, 0.207...   
4  [1.076010372088713, -0.8717434618548155, 0.207...   

                                              action  \
0  [1.076010372088713, -0.8717434618548155, 0.207...   
1  [1.076010372088713, -0.8717434618548155, 0.207...   
2  [1.076010372088713, -0.8717434618548155, 0.207...   
3  [1.076010372088713, -0.8717434618548155, 0.207...   
4  [1.076010372088713, -0.8717434618548155, 0.207...   

                          observation.meta.tool_type  timestamp  frame_index  \
0  [LARGE_NEEDLE_DRIVER:420006[..11], LARGE_NEEDL...   0.000000            0   
1  [LARGE_NEEDLE_DRIVER:420006[..11], LARGE_NEEDL...   0.030828            1   
2  [LARGE_NEEDLE_DRIVER:420006[..11], LARGE_NEEDL...   0.060528            2   
3  [LARGE_NEEDLE_DRIVER:420006[..11], LARGE_NEEDL...   0.090871            3   
4  [LARGE_NEEDLE_DRIVER:420006[..11], LARGE_NEEDL...   0.131323            4   

   episode_index  index  task_index  
0              0      0           0  
1              0      1           0  
2              0      2           0  
3              0      3           0  
4              0      4           0

In [4]:
file_path = "/home/stanford/catkin_ws/src/Autonomous-Surgical-Robot-Data/Needle Transfer Chetan LeRobot/data/chunk-000/episode_000000.parquet"
df_reference = pd.read_parquet(file_path)
df_reference.head()

observation.state  \
0  [1.0918771360074917, -0.904699136774942, 0.209...   
1  [1.0918771360074917, -0.904699136774942, 0.209...   
2  [1.0918771360074917, -0.904699136774942, 0.209...   
3  [1.0918771360074917, -0.904699136774942, 0.209...   
4  [1.0918771360074917, -0.904699136774942, 0.209...   

                                              action  \
0  [1.0918771360074917, -0.904699136774942, 0.209...   
1  [1.0918771360074917, -0.904699136774942, 0.209...   
2  [1.0918771360074917, -0.904699136774942, 0.209...   
3  [1.0918771360074917, -0.904699136774942, 0.209...   
4  [1.0918771360074917, -0.904699136774942, 0.209...   

                          observation.meta.tool_type  timestamp  frame_index  \
0  [LARGE_NEEDLE_DRIVER:420006[..11], LARGE_NEEDL...    0.00000            0   
1  [LARGE_NEEDLE_DRIVER:420006[..11], LARGE_NEEDL...    0.03011            1   
2  [LARGE_NEEDLE_DRIVER:420006[..11], LARGE_NEEDL...    0.06039            2   
3  [LARGE_NEEDLE_DRIVER:420006[..11], LARGE_NEEDL...    0.09017            3   
4  [LARGE_NEEDLE_DRIVER:420006[..11], LARGE_NEEDL...    0.13021            4   

   episode_index  index  task_index  
0              4   1522           0  
1              4   1523           0  
2              4   1524           0  
3              4   1525           0  
4              4   1526           0

In [18]:
df_reference.columns

Index(['observation.state', 'action', 'observation.meta.force_torque',
       'observation.meta.probe_type',
       'observation.meta.probe_acquisition_param',
       'observation.meta.tpv_cali_mtx', 'observation.meta.prob_cali_mtx',
       'timestamp', 'frame_index', 'episode_index', 'index', 'task_index'],
      dtype='object')

In [25]:
episode_stats_path = "/home/stanford/catkin_ws/src/Autonomous-Surgical-Robot-Data/LeRobot/Data/dummy_lerobot_dataset/meta/episodes_stats.jsonl"
with open(episode_stats_path, "r", encoding="utf-8") as f:
    episode_stats = [json.loads(line) for line in f if line.strip()]

In [39]:
episode_index = 1
stats = episode_stats[episode_index]['stats']

for state in stats:
    print(stats[state]['count'])

[30]
[30]
[30]
[30]
[30]
[30]
[30]
[30]
[30]
[30]
[30]
[30]
[30]


In [48]:
(df_reference['observation.state']).values

array([array([-1.7141811 ,  0.77277637,  1.8942045 , -1.9734719 , -0.17035095,
               1.5253704 ,  0.93571633], dtype=float32)                       ,
       array([-1.7141801 ,  0.77277476,  1.8942081 , -1.9734719 , -0.17035025,
               1.5253725 ,  0.9357215 ], dtype=float32)                       ,
       array([-1.7141749 ,  0.77277476,  1.894204  , -1.9734738 , -0.17034964,
               1.5253725 ,  0.9357162 ], dtype=float32)                       ,
       array([-1.7141746 ,  0.77277476,  1.8942076 , -1.9734739 , -0.17034963,
               1.5253718 ,  0.93571925], dtype=float32)                       ,
       array([-1.714177  ,  0.7727764 ,  1.8942057 , -1.9734702 , -0.17035025,
               1.5253711 ,  0.9357215 ], dtype=float32)                       ,
       array([-1.7141762 ,  0.7727764 ,  1.8942057 , -1.9734719 , -0.17034893,
               1.5253718 ,  0.9357196 ], dtype=float32)                       ,
       array([-1.7141795 ,  0.77277476,  1.894

In [ ]:
import numpy as np
import pandas as pd

def episode_stats_from_df(df, episode_index):
    out = {"episode_index": int(episode_index), "stats": {}}
    
    if "episode_index" in df.columns:
        df = df[df["episode_index"] == episode_index]
    else:
        print("Episode Index not found in the passed dataframe")
    
    for col in df.columns:
        s = df[col].dropna()
        if s.empty:
            continue
        
        # numeric scalar column
        if pd.api.types.is_numeric_dtype(s):
            vals = s.values.astype(float)
            out["stats"][col] = {
                "min": [float(vals.min())],
                "max": [float(vals.max())],
                "mean": [float(vals.mean())],
                "std": [float(vals.std(ddof=0))],
                "count": [len(vals)]
            }
            continue
        
        # try array-like column (observation.state, action, etc)
        try:
            arrs = [np.asarray(v, dtype=float) for v in s]
            stacked = np.stack(arrs, axis=0)  # shape: (N, ...)
            
            out["stats"][col] = {
                "min": stacked.min(axis=0).tolist(),
                "max": stacked.max(axis=0).tolist(),
                "mean": stacked.mean(axis=0).tolist(),
                "std": stacked.std(axis=0, ddof=0).tolist(),
                "count": [len(stacked)]
            }
        except (ValueError, TypeError):
            # skip non-numeric columns (strings, mixed types, etc)
            continue
    
    return out

{'min': [-1.7141823768615723,
  0.7727711200714111,
  1.8942021131515503,
  -1.9734759330749512,
  -0.17035289108753204,
  1.5253703594207764,
  0.9357154965400696],
 'max': [-1.7141741514205933,
  0.7727797627449036,
  1.8942086696624756,
  -1.973468542098999,
  -0.1703489124774933,
  1.5253732204437256,
  0.9357228875160217],
 'mean': [-1.7141778429349264,
  0.7727749526500702,
  1.8942055861155191,
  -1.9734718958536783,
  -0.17035025854905447,
  1.5253715753555297,
  0.9357189456621806],
 'std': [2.114295487486743e-06,
  1.715547591486498e-06,
  1.6557460349650486e-06,
  1.6611728833192135e-06,
  1.0235650420120652e-06,
  6.946946279684766e-07,
  1.9529798376342564e-06],
 'count': [30]}

In [81]:
out = episode_stats_from_df(df_reference,0)
out

{'episode_index': 0,
 'stats': {'observation.state': {'min': [-1.7141823768615723,
    0.7727711200714111,
    1.8942021131515503,
    -1.9734759330749512,
    -0.17035289108753204,
    1.5253703594207764,
    0.9357154965400696],
   'max': [-1.7141741514205933,
    0.7727797627449036,
    1.8942086696624756,
    -1.973468542098999,
    -0.1703489124774933,
    1.5253732204437256,
    0.9357228875160217],
   'mean': [-1.7141778429349264,
    0.7727749526500702,
    1.8942055861155191,
    -1.9734718958536783,
    -0.17035025854905447,
    1.5253715753555297,
    0.9357189456621806],
   'std': [2.114295487486743e-06,
    1.715547591486498e-06,
    1.6557460349650486e-06,
    1.6611728833192135e-06,
    1.0235650420120652e-06,
    6.946946279684766e-07,
    1.9529798376342564e-06],
   'count': [30]},
  'action': {'min': [0.4804018437862396,
    -0.04332757368683815,
    0.5094276666641235,
    -2.886733055114746,
    0.5138399004936218,
    -0.5150890350341797],
   'max': [0.480403214693

In [79]:
episode_stats[0]

{'episode_index': 0,
 'stats': {'observation.images.ultrasound': {'min': [[[0.0]],
    [[0.0]],
    [[0.0]]],
   'max': [[[0.7529411764705882]],
    [[0.7529411764705882]],
    [[0.7529411764705882]]],
   'mean': [[[0.049230446410334965]],
    [[0.049230446410334965]],
    [[0.049230446410334965]]],
   'std': [[[0.11070536426516839]],
    [[0.11070536426516839]],
    [[0.11070536426516839]]],
   'count': [30]},
  'observation.images.tpv_camera': {'min': [[[0.0]],
    [[0.0196078431372549]],
    [[0.0]]],
   'max': [[[1.0]], [[1.0]], [[1.0]]],
   'mean': [[[0.45905676947699653]],
    [[0.466696226830576]],
    [[0.46672813864315255]]],
   'std': [[[0.27719108267259024]],
    [[0.2819520578647853]],
    [[0.2750888255290673]]],
   'count': [30]},
  'observation.state': {'min': [-1.7141823768615723,
    0.7727711200714111,
    1.8942021131515503,
    -1.9734759330749512,
    -0.17035289108753204,
    1.5253703594207764,
    0.9357154965400696],
   'max': [-1.7141741514205933,
    0.772779

In [89]:
# python
def compare_stats_dicts(dict1, dict2, tol=1e-6):
    """
    Compare two stats dictionaries. Returns a summary of differences.
    
    Args:
        dict1: First stats dict (can have fewer keys)
        dict2: Second stats dict (reference, can have more keys)
        tol: Tolerance for floating point comparison (default 1e-6)
    
    Returns:
        dict with 'missing_keys', 'extra_keys', 'mismatched_keys', 'matched_keys', and 'all_match' flag
    """
    result = {
        'missing_keys': [],  # keys in dict2 but not in dict1
        'extra_keys': [],    # keys in dict1 but not in dict2
        'mismatched_keys': {},  # keys where values differ beyond tolerance
        'matched_keys': [],  # keys that match perfectly
        'all_match': True
    }
    
    stats1 = dict1.get('stats', dict1)
    stats2 = dict2.get('stats', dict2)
    
    keys1 = set(stats1.keys())
    keys2 = set(stats2.keys())
    
    result['missing_keys'] = sorted(keys2 - keys1)
    result['extra_keys'] = sorted(keys1 - keys2)
    
    if result['missing_keys'] or result['extra_keys']:
        result['all_match'] = False
    
    # Compare common keys
    common_keys = keys1 & keys2
    for key in common_keys:
        val1 = stats1[key]
        val2 = stats2[key]
        
        key_matches = True
        # Compare each stat field (min, max, mean, std, count)
        for stat_name in ['min', 'max', 'mean', 'std', 'count']:
            if stat_name not in val1 or stat_name not in val2:
                continue
            
            arr1 = np.asarray(val1[stat_name], dtype=float).flatten()
            arr2 = np.asarray(val2[stat_name], dtype=float).flatten()
            
            if arr1.shape != arr2.shape:
                if key not in result['mismatched_keys']:
                    result['mismatched_keys'][key] = {}
                result['mismatched_keys'][key][stat_name] = {
                    'reason': 'shape_mismatch',
                    'shape1': arr1.shape,
                    'shape2': arr2.shape
                }
                result['all_match'] = False
                key_matches = False
                continue
            
            # Check if values are within tolerance
            if not np.allclose(arr1, arr2, atol=tol, rtol=0):
                max_diff = np.abs(arr1 - arr2).max()
                if key not in result['mismatched_keys']:
                    result['mismatched_keys'][key] = {}
                result['mismatched_keys'][key][stat_name] = {
                    'reason': 'value_mismatch',
                    'max_diff': float(max_diff),
                    'value1_sample': arr1[:3].tolist() if len(arr1) > 0 else [],
                    'value2_sample': arr2[:3].tolist() if len(arr2) > 0 else []
                }
                result['all_match'] = False
                key_matches = False
        
        if key_matches:
            result['matched_keys'].append(key)
    
    return result

# Test it
comparison = compare_stats_dicts(out['stats'], episode_stats[2]['stats'])
print("Missing keys:", comparison['missing_keys'])
print("Extra keys:", comparison['extra_keys'])
print(f"\nMatched columns ({len(comparison['matched_keys'])}):")
for key in sorted(comparison['matched_keys']):
    print(f"  ✓ {key}")
print("\nAll match:", comparison['all_match'])
if comparison['mismatched_keys']:
    print(f"\nMismatched columns ({len(comparison['mismatched_keys'])}):")
    for key, mismatches in comparison['mismatched_keys'].items():
        print(f"  ✗ {key}:")
        for stat, details in mismatches.items():
            print(f"    {stat}: {details}")

Missing keys: ['observation.images.tpv_camera', 'observation.images.ultrasound']
Extra keys: []

Matched columns (5):
  ✓ frame_index
  ✓ observation.meta.prob_cali_mtx
  ✓ observation.meta.probe_acquisition_param
  ✓ observation.meta.tpv_cali_mtx
  ✓ timestamp

All match: False

Mismatched columns (6):
  ✗ observation.meta.force_torque:
    min: {'reason': 'value_mismatch', 'max_diff': 0.004183530807495117, 'value1_sample': [1.5567189455032349, 1.6771129369735718, -2.900928020477295], 'value2_sample': [1.5592634677886963, 1.6793723106384277, -2.8967444896698]}
    max: {'reason': 'value_mismatch', 'max_diff': 0.0022335052490234375, 'value1_sample': [1.5645326375961304, 1.6838634014129639, -2.8845717906951904], 'value2_sample': [1.5658292770385742, 1.6860969066619873, -2.8845014572143555]}
    mean: {'reason': 'value_mismatch', 'max_diff': 0.002913165092468306, 'value1_sample': [1.561427640914917, 1.680341076850891, -2.890936493873596], 'value2_sample': [1.5625941753387451, 1.683254241

In [83]:
out

{'episode_index': 0,
 'stats': {'observation.state': {'min': [-1.7141823768615723,
    0.7727711200714111,
    1.8942021131515503,
    -1.9734759330749512,
    -0.17035289108753204,
    1.5253703594207764,
    0.9357154965400696],
   'max': [-1.7141741514205933,
    0.7727797627449036,
    1.8942086696624756,
    -1.973468542098999,
    -0.1703489124774933,
    1.5253732204437256,
    0.9357228875160217],
   'mean': [-1.7141778429349264,
    0.7727749526500702,
    1.8942055861155191,
    -1.9734718958536783,
    -0.17035025854905447,
    1.5253715753555297,
    0.9357189456621806],
   'std': [2.114295487486743e-06,
    1.715547591486498e-06,
    1.6557460349650486e-06,
    1.6611728833192135e-06,
    1.0235650420120652e-06,
    6.946946279684766e-07,
    1.9529798376342564e-06],
   'count': [30]},
  'action': {'min': [0.4804018437862396,
    -0.04332757368683815,
    0.5094276666641235,
    -2.886733055114746,
    0.5138399004936218,
    -0.5150890350341797],
   'max': [0.480403214693

## Stanford dVRK Data

In [23]:
path2 = "/home/stanford/catkin_ws/src/Autonomous-Surgical-Robot-Data/LeRobot/Data/dummy_object_transfer/data/chunk-000/episode_000000.parquet"
df = pd.read_parquet(path2)

df.columns

Index(['observation.state', 'action', 'observation.meta.tool_type',
       'timestamp', 'frame_index', 'episode_index', 'index', 'task_index'],
      dtype='object')

In [24]:
df

observation.state  \
0    [0.8305486999236953, -0.8286413176780271, 0.10...   
1    [0.8305486999236953, -0.8286413176780271, 0.10...   
2    [0.8305486999236953, -0.8286413176780271, 0.10...   
3    [0.8305486999236953, -0.8286413176780271, 0.10...   
4    [0.8305486999236953, -0.8286413176780271, 0.10...   
..                                                 ...   
445  [1.0189348028044518, -0.8248651308375476, 0.11...   
446  [1.0189992383333242, -0.8248486621197801, 0.11...   
447  [1.0190803429432225, -0.8248446862940967, 0.11...   
448  [1.0191228533993606, -0.8248979766938209, 0.11...   
449  [1.0192029427277454, -0.8250486528314899, 0.11...   

                                                action  \
0    [0.8305486999236953, -0.8286413176780271, 0.10...   
1    [0.8305486999236953, -0.8286413176780271, 0.10...   
2    [0.8305486999236953, -0.8286413176780271, 0.10...   
3    [0.8305486999236953, -0.8286413176780271, 0.10...   
4    [0.8305486999236953, -0.8286413176780271, 0.10...   
..                                                 ...   
445  [1.0189992383333242, -0.8248486621197801, 0.11...   
446  [1.0190803429432225, -0.8248446862940967, 0.11...   
447  [1.0191228533993606, -0.8248979766938209, 0.11...   
448  [1.0192029427277454, -0.8250486528314899, 0.11...   
449  [1.019390439656295, -0.8251778434050587, 0.117...   

                            observation.meta.tool_type  timestamp  \
0    [FENESTRATED_BIPOLAR_FORCEPS:420205, FENESTRAT...   0.000000   
1    [FENESTRATED_BIPOLAR_FORCEPS:420205, FENESTRAT...   0.030594   
2    [FENESTRATED_BIPOLAR_FORCEPS:420205, FENESTRAT...   0.061276   
3    [FENESTRATED_BIPOLAR_FORCEPS:420205, FENESTRAT...   0.100598   
4    [FENESTRATED_BIPOLAR_FORCEPS:420205, FENESTRAT...   0.130849   
..                                                 ...        ...   
445  [FENESTRATED_BIPOLAR_FORCEPS:420205, FENESTRAT...  14.843927   
446  [FENESTRATED_BIPOLAR_FORCEPS:420205, FENESTRAT...  14.874250   
447  [FENESTRATED_BIPOLAR_FORCEPS:420205, FENESTRAT...  14.914244   
448  [FENESTRATED_BIPOLAR_FORCEPS:420205, FENESTRAT...  14.944563   
449  [FENESTRATED_BIPOLAR_FORCEPS:420205, FENESTRAT...  14.975465   

     frame_index  episode_index  index  task_index  
0              0              0      0           0  
1              1              0      1           0  
2              2              0      2           0  
3              3              0      3           0  
4              4              0      4           0  
..           ...            ...    ...         ...  
445          445              0    445           0  
446          446              0    446           0  
447          447              0    447           0  
448          448              0    448           0  
449          449              0    449           0  

[450 rows x 8 columns]